=== julstan/projectOBib-Search/ojs/lib/pkp/dtd/emailTemplateData.dtd
<!--
  * dtd/emailTexts.dtd
  *
  * Copyright (c) 2014-2020 Simon Fraser University
  * Copyright (c) 2000-2020 John Willinsky
  * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
  *
  * DTD for email texts.
  *
  -->

<!ELEMENT email_texts (email_text*)>
	<!ATTLIST email_texts
		locale CDATA #REQUIRED>
<!ELEMENT email_text (subject, body, description?)>
	<!ATTLIST email_text
		key CDATA #REQUIRED>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== julstan/projectOBib-Search/ojs/plugins/generic/lucene/locale/ar_IQ/emailTemplates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email_texts SYSTEM "../../../../../lib/pkp/dtd/emailTemplateData.dtd">

<!--
  * @file locale/ar_IQ/emailTemplates.xml
  *
  * Copyright (c) 2013-2020 Simon Fraser University
  * Copyright (c) 2003-2020 John Willinsky
  * Distributed under the GNU GPL v2. For full terms see the file docs/COPYING.
  *
  * Localized email templates XML file.
  -->

<email_texts locale="ar_IQ">
	<email_text key="LUCENE_ARTICLE_INDEXING_ERROR_NOTIFICATION">
		<subject>خطأ فهرسة المؤلَّف</subject>
		<body>حدث خطأ ما عند محاولة تعديل فهرس المؤلَّف.

رسالة الخطأ المولدة من قبل خدمة الإنترنت (إن وجدت): "{$error}"

هذه الرسالة أنشأها نظام المجلات المفتوحة عبر إضافة البحث Lucene.</body>
		<description>قالب هذه الرسالة مستعمل لإشعار عنوان الاتصال الفني في المجلة بأن خطأً ما حدث أثناء فهرسة أحد المؤلفات.</description>
	</email_text>
	<email_text key="LUCENE_JOURNAL_INDEXING_ERROR_NOTIFICATION">
		<subject>خطأ في فهرسة المجلة</subject>
		<body>حدث خطأ ما عند فهرسة المجلة "{$journalName}".

رسالة الخطأ المولدة من قبل خدمة الإنترنت (إن وجدت): "{$error}"

هذه الرسالة أنشأها نظام المجلات المفتوحة عبر إضافة البحث.</body>
		<description>قالب هذه الرسالة مستعمل لإشعار عنوان الاتصال الفني في المجلة بأن خطأً ما حدث أثناء فهرسة المجلة.</description>
	</email_text>
	<email_text key="LUCENE_SEARCH_SERVICE_ERROR_NOTIFICATION">
		<subject>خطأ في خدمة البحث في المجلة</subject>
		<body>حدث خطأ ما عند محاولة أحدهم البحث في "{$siteName}".

رسالة الخطأ المولدة من قبل خدمة الإنترنت (إن وجدت): "{$error}"

هذه الرسالة أنشأها نظام المجلات المفتوحة عبر إضافة البحث.</body>
		<description>قالب هذه الرسالة مستعمل لإشعار عنوان الاتصال الفني في المجلة بأن خطأً ما حدث أثناء محاولة استعمال خدمة البحث المجردة في الموقع.</description>
	</email_text>
</email_texts>
